### ISSUE TITLE
Invalid external files should fail gracefully

### ISSUE THREAD

**Issue by Jeff-Symphony** [dwightjack/grunt-nodemailer#11]
I had missed this line in the documentation:
```
Accepted file extensions are .html, .htm and .txt.
```
and was trying to use a .json file as the body of my email. 
The failure I was getting was:
`Fatal error: Error occured: Can't send mail - no recipients defined`
because the message was `false`.

One option would be to improve the if/else if clause to better handle different file types (or at least log the file types are invalid). 
Another option would be to add a test condition to `async.eachSeries(messages, function (msg, next) {`
```
		if (!msg) {
			grunt.fail.fatal('No message to send.');
		}
```

**Comment by dwightjack** [comment]
Thanx for the suggestion.

I will implement the first option.

Anyway Instead of using a file as email body source you should use the `message.html` option:

```
nodemailer: {
  json_email: {
    options: {
      message: {
        html: grunt.file.read('body.json')
        ...
      }
    }
  }
}
```

**Comment by dwightjack** [comment]
This should be fixed by the latest release
