### ISSUE TITLE
Image attachment has no data 

### ISSUE THREAD

**Issue by mycompassspins** [dwightjack/grunt-nodemailer#12]
Hey there,

Despite all the hair I've pulled outta my head over the last few hours, I love nodemailer :) I'm trying to send an image attachment and it's coming through, but with no data. 0kb in size. That's using this code:

    var path = require('path');
    var uploadDir = path.dirname(require.main.filename); 
    // This actually produces a filepath that starts at my /Applications dir on my Mac, but ends in the right spot.

    var img = require("fs").readFileSync(uploadDir + '/uploads/' + params.newFileName);
    // file was upload was handled on the server by multer and renamed to something like this: fc5c5921bd0892f114cd7b6f0d39d9a3.gif

    attachments: [{
        filename: params.newFileName,
        filePath: img
    }]

The image is in the directory, and there are no explicit errors. When I replace filePath above with path (as it's written in some places), I get an attachment called attachment-1.bin. I've also tried setting my img var as a value of the content property in the attachments object, to no avail. In fact I've probably tried about a hundred variations on the theme with no luck.

**Comment by mycompassspins** [comment]
Shoot, just realized this is for grunt-nodemailer. Closing it. Sorry.

**Comment by dwightjack** [comment]
No problem.
filePath should be the right option.
File attachment signature changed after v1 I guess, that's why you find different names around the web. 
Anyway in your example I think that it also should be a path to a file while you are passing in the file contents.
